### PR TITLE
Adding information about Sealy board

### PR DESCRIPTION
**Pull request by Randname666**
Chinese company. Most of the products are slot machines, but also ripoffs of some infamous rhythm games.

### CODE REVIEW

**Comment by DashLt** [comment]
I have a Let's Beat PCB coming in soon - I will be all too excited to contribute more info and pictures.

**Comment by Randname666** [comment]
> I have a Let's Beat PCB coming in soon - I will be all too excited to contribute more info and pictures.
Actually, there is just a Let's Beat PCB lying on my table. The funny thing is the PSU is stuck on the road and probably takes another week, if not two to arrive so I can't test it yet.

**Comment by DashLt** [comment]
Ha, incredible. Which other ones do you have? I haven't been able to find any Music Pinball PCBs, though I do see a Rushing Rhythm on xianyu...

**Comment by Randname666** [comment]
> Ha, incredible. Which other ones do you have? I haven't been able to find any Music Pinball PCBs, though I do see a Rushing Rhythm on xianyu...

That's the only one. Most of the others are slot machines which don't worth purchasing. Lazy assets swapped stuff.

**Pull request merged**
